### ISSUE TITLE
Add charset tag

### ISSUE THREAD

**Issue by tymees** [UiL-OTS-labs/jspsych-self-paced-reading-mw#1]
We should add ``<meta charset="UTF-8">`` to the template, to avoid annoying encoding problems

**Comment by maartenuni** [comment]
I'll add it to the header

**Comment by maartenuni** [comment]
Hmm, deze repository is ooit door Jacco gemaakt. misschien moeten we deze repository "sluiten". Het is denk ik niet handig om 2 repo's van ongeveer gelijke experimenten bij te houden.

**Comment by tymees** [comment]
Goed punt; ik was gisteren gewoon even alle repo's met jspsych in de naam langsgegaan om te kijken welke die tag misten. 

Nu ik er beter naar kijk zou ik inderdaad zeggen dat die andere geprefereerd zou moeten worden over deze
